### ISSUE TITLE
Example of completed / filled in 4D-OME XML

### ISSUE THREAD

**Issue by JacksonMaxfield** [WU-BIMAC/MicroscopyMetadata4DNGuidelines#18]
We are working on switching over to the 4D-OME spec and would greatly appreciate having a fully or near fully "complete" 4D-OME XML file as an example of what should be produced by any system that would be in-compliance with the specification.

Would there be a possibility of adding one to this repo or pointing me in the direction of where I may retrieve one?

**Comment by strambc** [comment]
HI Jackson
I am very excited about your interest.
Consistent with the current OME procedures, the 4DN-OME model is currently represented in xsd.
 
The latest version of the model is v06 and the XSD file can be found here:
https://github.com/WU-BIMAC/MicroscopyMetadata4DNGuidelines/tree/master/Model/stable%20version/v01-06

However, I am in the process of updating the model and making a significantly different new commit in the next couple of days.
So if you can wait until Monday next week I recommend you do so.

Also, keep in mind that the proposal is just that a proposal. 
We are currently involved in efforts to make sure the community has a chance to review the proposal, provide feedback and hopefully adopt it.

To this end, I have been invited to lead the BINA Quality Control and Data Management Working Group, whose first meeting will be in two weeks.

One of the goals of the WG will be to devise appropriate methods for vetting, reviewing and eventually approving the proposal.

**Comment by strambc** [comment]
All of this to say that the model proposal is very much a work in progress.
Also, you should be aware that together with the OME and RIKEN people we are in the process of producing OWL/RDF representations of the model in order to better support the evolution and further extension of the OME core ontology.

Let me know if you have any furhter questions.

**Comment by JacksonMaxfield** [comment]
The v01-07 version looks great! Thank you for including the schema diagrams as JPEG as well!

I noticed that there is a v01-08 in_progress as well, how long do you expect the current stable to be marked as stable and do you expect there to be breaking changes between the versions.

**Comment by Akramhar** [comment]
Hi @JacksonMaxfield,
The model is still going through development phases until we complete the Image Acquisition Settings side.
Sorry but atm I can't give you a precise timeline on the next iteration phases.
Realistically there may be breaking changes in the future due to the fact that some fields may still be renamed, moved and/or removed in the future releases.

**Comment by Akramhar** [comment]
To answer to your previous request, we currently don't produce complete xml output.
Our current implementation produce a json output with the "additional part" that we save separately.
We then connect the ome data with the "additional data" at the application level.
