### ISSUE TITLE
Change name of model files for publication

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroscopyMetadata4DNGuidelines#24]
All file names have to be changed and cleaned up for publication.

**Comment by SteveO-sudo** [comment]
Great Work!!!!

+1 For this enhancement. Not only for publication, but for readability on this site. You've encoded all the metadata about the file in the filename. Something we used to do with images, but are trying to get away from by ensuring image metadata is complete.  Do you see the irony? 
"4DN-BINA-OME-Microscopy Metadata_ER diagram_ADVANCED+CONFOCAL.graphml" could become "Advanced_Confocal.graphml". All the other stuff is superfluous and makes it hard to select files in the web browser under the "Model" folder because of the fixed width of the name column in the display. Every filename looks almost the same: "4DN-BINA-OME-Microscopy Metadata_ER diagram_A..."

**Comment by strambc** [comment]
Thank you for the comment.
Great idea I will definitely apply it.

**Comment by strambc** [comment]
DONE thank you for the suggestionon

**Comment by SteveO-sudo** [comment]
Perfect! Much easier to read now

Thank you

**Comment by strambc** [comment]
Let me know if you have other similarly insightful suggestions!
